### ISSUE TITLE
Replace weird qMin/qMax combinations with std::min, max and clamp

### ISSUE THREAD

**Issue by berkus** [procxx/tdesktop#36]
Code in many places uses qMin+qMax or even qMin+qMin to clamp values, just use std::clamp.

Probably replace qXxx versions with their std counterparts - ?

See [here](https://github.com/procxx/tdesktop/pull/25#discussion_r154543905) for reference.

Mini task-list (added by @leha-bot):
 - [x] std::min - done in #89 
 - [x] std::max  - done in #89
 - [ ] std::clamp - requested in #89 but postponed to another PR.
